# Generated by Django 4.2.4 on 2023-08-13 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="info",
            new_name="Date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="name",
            new_name="Name",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="price",
            new_name="Quantite",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="id",
            new_name="UPC",
        ),
    ]
