# Generated by Django 4.2.4 on 2023-08-13 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0004_alter_product_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="UPC",
            field=models.CharField(
                default=0, max_length=200, primary_key=True, serialize=False
            ),
        ),
    ]
