# Generated by Django 4.2.4 on 2023-08-13 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0006_alter_product_quantite_alter_product_upc"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Quantite",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
