# Generated by Django 4.2.4 on 2023-08-13 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0007_product_name_alter_product_quantite"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="Quantite",
        ),
        migrations.AlterField(
            model_name="product",
            name="Date",
            field=models.DateField(null=True),
        ),
    ]
