# Generated by Django 4.2.4 on 2023-08-13 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0008_remove_product_quantite_alter_product_date"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
        migrations.AddField(
            model_name="product",
            name="Quantite",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="Date",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="product",
            name="UPC",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name="product",
            name="Name",
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
