# Generated by Django 4.2.4 on 2023-08-13 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0011_alter_product_quantite"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="Date",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
