# Generated by Django 4.2.4 on 2023-08-13 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0012_alter_product_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Quantite",
            new_name="Qutite",
        ),
    ]
