# Generated by Django 4.2.4 on 2023-08-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0013_rename_quantite_product_qutite"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Qutite",
            new_name="Quantite",
        ),
    ]
