# Generated by Django 4.2.4 on 2023-08-13 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0016_alter_product_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Date",
            new_name="date",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="Quantite",
            new_name="quantite",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="UPC",
            new_name="upc",
        ),
    ]
