# Generated by Django 4.2.4 on 2023-08-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0017_rename_date_product_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Product_Label",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("label", models.CharField(max_length=200)),
            ],
        ),
    ]
