# Generated by Django 4.2.4 on 2023-08-14 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0018_product_label"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product_label",
            name="label",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
